version: 2.1

executors:
  gen1:
    macos:
      xcode: 13.4.1
  gen2:
    macos:
      xcode: 13.4.1
    resource_class: macos.x86.medium.gen2

jobs:
  firebase-no-upgrade:
    executor: gen2
    steps:
      - run: |
          curl -svL https://firebase.tools | bash
  firebase-with-upgrade:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - run: |
          # the upgrade=true is seen on https://firebase.google.com/docs/cli#macos
          curl -svL https://firebase.tools | upgrade=true bash
workflows:
  main:
    jobs:
      - firebase-no-upgrade